# Compile all java files
default: compile

compile:
	javac com/gradescope/DoubleQueue/code/*.java
	javac Driver/*.java

# Run the driver
run:
	java -cp . Driver.DoubleQueueDriver

# Remove all the .class files
clean:
	rm com/gradescope/DoubleQueue/code/*.class
	rm Driver/*.class



